import React, { useState } from 'react';
import { authService } from '../../services/authService';
import { useNavigate, Link } from 'react-router-dom';

export default function AdminLogin() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [otpCode, setOtpCode] = useState('');
  const [step, setStep] = useState(1);
  const [sessionToken, setSessionToken] = useState(null);
  
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const res = await authService.adminLogin(username, password);
      if (res.data.sessionToken || res.data.tempToken) {
        setSessionToken(res.data.sessionToken || res.data.tempToken);
        setStep(2);
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to log in as admin');
    } finally {
      setLoading(false);
    }
  };

  const handleOtpSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const response = await authService.adminVerifyOtp(sessionToken, otpCode);
      if (response.data.token) {
        localStorage.setItem('token', response.data.token);
        navigate('/admin/dashboard');
        window.location.reload();
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Invalid OTP code');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-md mx-auto mt-20 p-8 bg-slate-900 text-white rounded-md shadow-lg border border-slate-800">
      <div className="text-center mb-6">
        <span className="material-symbols-outlined text-4xl text-rose-500 mb-2">security</span>
        <h2 className="text-2xl font-bold">System Admin Access</h2>
      </div>
      
      {error && <div className="p-3 mb-4 text-sm text-rose-200 bg-rose-900/50 border-l-4 border-rose-500 rounded">{error}</div>}
      
      {step === 1 ? (
        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">Admin Username</label>
            <input
              type="text"
              className="w-full h-10 px-3 rounded-md border border-slate-700 bg-slate-800 text-white text-sm focus:border-rose-500 focus:ring-1 focus:ring-rose-500 outline-none transition-colors"
              value={username}
              onChange={e => setUsername(e.target.value)}
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">Master Password</label>
            <input
              type="password"
              className="w-full h-10 px-3 rounded-md border border-slate-700 bg-slate-800 text-white text-sm focus:border-rose-500 focus:ring-1 focus:ring-rose-500 outline-none transition-colors"
              value={password}
              onChange={e => setPassword(e.target.value)}
              required
            />
          </div>
          <button type="submit" disabled={loading} className="w-full py-2 bg-rose-600 hover:bg-rose-700 active:bg-rose-800 text-white font-medium text-sm rounded-md shadow-sm transition-colors mt-4">
            {loading ? 'Authenticating...' : 'Authenticate'}
          </button>
          <div className="text-center mt-4 text-sm">
            <Link to="/login" className="text-slate-400 hover:text-white">Return to Standard Login</Link>
          </div>
        </form>
      ) : (
        <form onSubmit={handleOtpSubmit} className="space-y-4">
          <div className="text-center text-sm text-slate-300 mb-4">
            Enter the 2FA code generated by your authenticator app.
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">Secure OTP Code</label>
            <input
              type="text"
              className="w-full h-12 px-3 rounded-md border border-slate-700 bg-slate-800 text-white text-xl text-center tracking-widest focus:border-rose-500 focus:ring-1 focus:ring-rose-500 outline-none transition-colors"
              value={otpCode}
              onChange={e => setOtpCode(e.target.value)}
              required
              maxLength={6}
            />
          </div>
          <button type="submit" disabled={loading} className="w-full py-2 bg-rose-600 hover:bg-rose-700 active:bg-rose-800 text-white font-medium text-sm rounded-md shadow-sm transition-colors mt-4">
            {loading ? 'Verifying...' : 'Verify Secure Login'}
          </button>
        </form>
      )}
    </div>
  );
}
